FROM nginx:latest
COPY index.html /usr/share/nginx/html
COPY index.js /usr/share/nginx/html
COPY styles.css /usr/share/nginx/html
COPY login.html /usr/share/nginx/html
COPY login.js /usr/share/nginx/html
COPY register.html /usr/share/nginx/html
COPY register.js /usr/share/nginx/html
COPY delete.html /usr/share/nginx/html
COPY delete.js /usr/share/nginx/html
COPY options.html /usr/share/nginx/html
COPY options.js /usr/share/nginx/html